### get user profile
GET {{host}}/v1/user/profile
Authorization: {{token}}
Accept: application/json

### get balance
GET {{host}}/v1/accounts/{{account}}/balances
Authorization: {{token}}
Accept: application/json

### Get an option’s expiration dates
GET {{host}}/v1/markets/options/expirations?includeAllRoots=true&contractSize=true&expirationType=true&symbol=SPY
Authorization: {{token}}
Accept: application/json

### Get an option chain
GET {{host}}/v1/markets/options/chains?greeks=true&expiration=2024-04-19&symbol=SPY
Authorization: {{token}}
Accept: application/json

### Get Quotes
GET {{host}}/v1/markets/quotes?greeks=true&symbols=SPY240419C00490000
Authorization: {{token}}
Accept: application/json

### Get an account’s orders
GET {{host}}/v1/accounts/{{account}}/orders
Authorization: {{token}}
Accept: application/json

### Get an account’s history
GET {{host}}/v1/accounts/{{account}}/history
Authorization: {{token}}
Accept: application/json

### Get the intraday status
GET {{host}}/v1/markets/clock
Authorization: {{token}}
Accept: application/json

### Get the market calendar
GET {{host}}/v1/markets/calendar
Authorization: {{token}}
Accept: application/json

### get risk free rate
GET https://ycharts.com/indicators/3_month_t_bill
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0